### ISSUE TITLE
DSGPUImage pod install error.

### ISSUE THREAD

**Issue by jinguohao1991** [StraaS/StraaS-iOS-sdk#194]
Hi, How are you?
I tried to use 'StraaS-iOS-SDK/Streaming' but I got an issue while installing pod files.
This is the error code I got.
I expect your kind help.
Thank you.

Installing DSGPUImage (0.1.8)

[!] Error installing DSGPUImage
[!] /usr/bin/git clone https://github.com/dubsmash/GPUImage.git /var/folders/6p/b3nl3hkj2bg9m95_lxqxkj400000gn/T/d20191012-15190-11hscoe --template= --single-branch --depth 1 --branch 0.1.8

Cloning into '/var/folders/6p/b3nl3hkj2bg9m95_lxqxkj400000gn/T/d20191012-15190-11hscoe'...
remote: Repository not found.
fatal: repository 'https://github.com/dubsmash/GPUImage.git/' not found

**Comment by ikala-FAE** [comment]
Only after passing the validation, developer can start using services in StraaS SDK.
Make sure you've apply the official account from [StraaS.io](https://cms.straas.io).

If you don't have official account, just go to [Contact](https://straas.io/contact/) page to fill the form to apply official account. If you already official account, then email to FAE/Sales of StraaS. Thanks.

**Comment by jinguohao1991** [comment]
Hi, ikala-FAE. Thank you for your kind reply.

**Comment by junghao** [comment]
@ikala-FAE So we'll be able to access the repo https://github.com/dubsmash/GPUImage after we've become a Straas developer?

Thanks.

**Comment by ikala-FAE** [comment]
@junghao  The repo https://github.com/dubsmash/GPUImage was just removed few days ago. we are searching a new solution to solve this problem. It will be fixed in one month.

If you have any question about StraaS. I recommend you to [contact us](https://straas.io/zh-TW/contact/). Then we can use email, phone or face-to-face to introduce StraaS solution for you.

Thanks.
